import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import theme from "@/themes/theme";
import { ThemeProvider } from "@mui/material/styles";
import BaseLayout from "@/components/layout/BaseLayout";
import CssBaseline from "@mui/material/CssBaseline";
export const metadata: Metadata = {
  title: "Clickatell Sample",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <BaseLayout>{children}</BaseLayout>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
